---
abstract: 'generate pleasant color schemes'
author:
  - 'Ian Langworth <ian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Color-Scheme
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 1.14
  POSIX: 1.08
  Test::Differences: 0.47
  Test::More: 0.54
version: 1.03
